name: Validate pull request
on:
  pull_request:
    branches:
      - main-disabled
jobs:
  plan:
    strategy:
      matrix:
        environment:
          - nonprod
          - common
    name: Plan ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Plan
        uses: catalystcommunity/action-terraform@v1
        with:
          command: plan
          work-dir: ${{ matrix.environment }}
          provider: aws
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
